# Generated by Django 5.2.3 on 2025-06-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_datosusuariom_delete_datosgenerales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosusuariom',
            name='giro',
        ),
        migrations.AddField(
            model_name='datosusuariom',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
