# Generated by Django 5.2.3 on 2025-06-19 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_remove_datosusuariom_giro_datosusuariom_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='declaratoriaPropiedadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueñoDP', models.CharField(max_length=255)),
                ('empresaDP', models.CharField(max_length=255)),
                ('rfcDP', models.CharField(max_length=13)),
                ('domicilioDP', models.CharField(max_length=255)),
                ('emailDP', models.EmailField(max_length=255)),
                ('telefonoDP', models.CharField(max_length=30)),
                ('reprelegalDP', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
