# Generated by Django 5.2.3 on 2025-06-24 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0005_declaratoriacumplimientoambientalmoodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='declaCumpliAmbiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresaDCA', models.CharField(max_length=255)),
                ('domiciloDCA', models.CharField(max_length=255)),
                ('representanteDCA', models.CharField(max_length=255)),
                ('rfcDCA', models.CharField(max_length=13)),
                ('ubicacionDCA', models.CharField(max_length=255)),
                ('expedienteDCA', models.CharField(max_length=255)),
                ('responsableDCA', models.CharField(max_length=255)),
                ('cedulaDCA', models.CharField(max_length=255)),
                ('emailDCA', models.EmailField(max_length=255)),
                ('telefonoDCA', models.CharField(max_length=30)),
                ('diaDCA', models.CharField(max_length=2)),
                ('mesDCA', models.CharField(max_length=20)),
                ('yearDCA', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='declaratoriaCumplimientoAmbientalMoodel',
        ),
    ]
