# Generated by Django 5.2.3 on 2025-06-24 23:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0006_declacumpliambimodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='declaCumpliAmbiModel',
            new_name='declaCumpliAmbModel',
        ),
        migrations.RenameField(
            model_name='declacumpliambmodel',
            old_name='domiciloDCA',
            new_name='domicilioDCA',
        ),
    ]
