# Generated by Django 5.2.3 on 2025-06-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0007_rename_declacumpliambimodel_declacumpliambmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declacumpliambmodel',
            name='mesDCA',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='declacumpliambmodel',
            name='telefonoDCA',
            field=models.CharField(max_length=12),
        ),
    ]
