# Generated by Django 5.2.3 on 2025-06-26 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0008_alter_declacumpliambmodel_mesdca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cartaNotificacionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugarCN', models.CharField(max_length=255)),
                ('diaCN', models.CharField(max_length=2)),
                ('mesCN', models.CharField(max_length=2)),
                ('anioCN', models.CharField(max_length=4)),
                ('nombreNotCN', models.CharField(max_length=255)),
                ('domicilioNotCN', models.CharField(max_length=255)),
                ('nomRemiCN', models.CharField(max_length=255)),
                ('cargoRemiCN', models.CharField(max_length=255)),
                ('depaRemiCN', models.CharField(max_length=255)),
                ('motivoCN', models.TextField(max_length=500)),
                ('objetivoCN', models.TextField(max_length=500)),
                ('plazoCN', models.CharField(max_length=255)),
                ('ubiDepenCN', models.CharField(max_length=255)),
                ('horarioCN', models.CharField(max_length=255)),
                ('telDepenCN', models.CharField(max_length=12)),
                ('emailDepenCN', models.EmailField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
