# Generated by Django 5.2.3 on 2025-06-26 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0009_cartanotificacionmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reporteVisitaTecnicaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudadRVT', models.CharField(max_length=255)),
                ('horaRVT', models.TimeField()),
                ('diaRVT', models.CharField(max_length=2)),
                ('mesRVT', models.CharField(max_length=2)),
                ('yearRVT', models.CharField(max_length=4)),
                ('inspectorRVT', models.CharField(max_length=255)),
                ('cargoRVT', models.CharField(max_length=255)),
                ('departamentoRVT', models.CharField(max_length=255)),
                ('nomEstableRVT', models.CharField(max_length=255)),
                ('direcEstableRVT', models.CharField(max_length=255)),
                ('motivoVisitaRVT', models.TextField(max_length=500)),
                ('condiciSeguRVT', models.TextField(max_length=500)),
                ('manejoResiduosRVT', models.TextField(max_length=500)),
                ('cumpliNormasRVT', models.TextField(max_length=500)),
                ('observacionesRVT', models.TextField(max_length=500)),
                ('nombreResponsRVT', models.CharField(max_length=255)),
                ('tipoIdentificacionRVT', models.CharField(max_length=255)),
                ('numIdentificacionRVT', models.CharField(max_length=255)),
                ('emailEstableciRVT', models.EmailField(max_length=255)),
                ('telefonoEstableciRVT', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
