# Generated by Django 5.2.3 on 2025-06-27 20:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0010_reportevisitatecnicamodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='inventarioOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escriCant', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(999)])),
                ('escriModelo', models.CharField(max_length=255)),
                ('escriCondicion', models.CharField(max_length=255)),
                ('escriUbi', models.CharField(max_length=255)),
                ('escriObservaciones', models.TextField(max_length=500)),
                ('sillaCant', models.PositiveBigIntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(999)])),
                ('sillaModelo', models.CharField(max_length=255)),
                ('sillaCondicion', models.CharField(max_length=255)),
                ('sillaUbi', models.CharField(max_length=255)),
                ('sillaObservacion', models.TextField(max_length=500)),
                ('LapCant', models.PositiveBigIntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(999)])),
                ('LapModelo', models.CharField(max_length=255)),
                ('LapCondicion', models.CharField(max_length=255)),
                ('LapUbi', models.CharField(max_length=255)),
                ('LapObservacion', models.TextField(max_length=500)),
                ('proyecCant', models.PositiveBigIntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(999)])),
                ('proyecModelo', models.CharField(max_length=255)),
                ('proyecCondicion', models.CharField(max_length=255)),
                ('proyecUbi', models.CharField(max_length=255)),
                ('proyecObservacion', models.TextField(max_length=500)),
                ('impreCant', models.PositiveBigIntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(999)])),
                ('impreModelo', models.CharField(max_length=255)),
                ('impreCondicion', models.CharField(max_length=255)),
                ('impreUbi', models.CharField(max_length=255)),
                ('impreObservacion', models.TextField(max_length=500)),
                ('aguaCant', models.PositiveBigIntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(999)])),
                ('aguaModelo', models.CharField(max_length=255)),
                ('aguaCondicion', models.CharField(max_length=255)),
                ('aguaUbi', models.CharField(max_length=255)),
                ('aguaObservacion', models.TextField(max_length=500)),
                ('escobCant', models.PositiveBigIntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(999)])),
                ('escobModelo', models.CharField(max_length=255)),
                ('escobCondicion', models.CharField(max_length=255)),
                ('escobUbi', models.CharField(max_length=255)),
                ('escobObservacion', models.TextField(max_length=500)),
                ('extintCant', models.PositiveBigIntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(999)])),
                ('extintModelo', models.CharField(max_length=255)),
                ('extintCondicion', models.CharField(max_length=255)),
                ('extintUbi', models.CharField(max_length=255)),
                ('extintObservacion', models.TextField(max_length=500)),
                ('jabonCant', models.PositiveBigIntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(999)])),
                ('jabonModelo', models.CharField(max_length=255)),
                ('jabonCondicion', models.CharField(max_length=255)),
                ('jabonUbi', models.CharField(max_length=255)),
                ('jabonObservacion', models.TextField(max_length=500)),
                ('hojasCant', models.PositiveBigIntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(999)])),
                ('hojasModelo', models.CharField(max_length=255)),
                ('hojasCondicion', models.CharField(max_length=255)),
                ('hojasUbi', models.CharField(max_length=255)),
                ('hojasObservacion', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
